### ISSUE TITLE
幼盾上的star数比真实star数小

### ISSUE THREAD

**Issue by sb-child** [RimoChan/unv-shield#1]
如图
![IMG_20210718_012431](https://user-images.githubusercontent.com/55868015/126045016-f7379610-4545-4078-ab5f-6a356a50176a.jpg)
![IMG_20210718_012451](https://user-images.githubusercontent.com/55868015/126045021-da2e6384-0f8d-4ad9-a25d-ae941cd794eb.jpg)

**Comment by RimoChan** [comment]
这是正常的，因为CDN有4个小时的缓存时间。

**Comment by sb-child** [comment]
(这个数字维持了几天..
cdn怕是出了问题

**Comment by RimoChan** [comment]
![image](https://user-images.githubusercontent.com/20064807/126054841-938a6970-dfdb-43bc-9bd2-4bb0a6f152e6.png)

啊我这里看到的是1啊。
在7月3号之前我没有加cache-control，如果那之前在GitHub上用过的话会有缓存不能更新的问题，但是你好像已经超过7月3号了……

**Comment by RimoChan** [comment]
对了，你把链接里的 `code=1&` 去掉应该就好了！

**Comment by sb-child** [comment]
> 对了，你把链接里的 `code=1&` 去掉应该就好了！

~~啊我试试~~

幼女好棒~  过亿段时间再看看吧!
